### ISSUE TITLE
"Test" failed after "Build"

### ISSUE THREAD

**Issue by YanfeiNREL** [urbanopt/geojson-modelica-translator#12] opened 2019-11-12 00:10 UTC
My test failed after build the product.
Reason: it looks for the "test" folder in TEASEROutput/Project/TestBuilding/, which is an external folder parallell to geojson-modelica-translator. 
Solution-1: i copied the "test" folder within geojson-modelica-translator, to replace the "test" folder in TEASEROutput. The tests all passed. 
Solution-2: py.test tests

The error message are in the attachment: failure.txt.
[failures.txt](https://github.com/urbanopt/geojson-modelica-translator/files/3833709/failures.txt)

**Comment by nllong** [comment] 2019-12-06 15:15
Duplicate of #16

**Closed by nllong** 2019-12-06 15:15 UTC
