### ISSUE TITLE
Failing tests - py test trying to run teaser tests

### ISSUE THREAD

**Issue by AntoineGautier** [urbanopt/geojson-modelica-translator#16] opened 2019-11-14 21:56 UTC
@nllong As discussed: attached are the pytest log and the list of the installed packages in my Python environment.
[pytest.log](https://github.com/urbanopt/geojson-modelica-translator/files/3848781/pytest.log)
[versions.txt](https://github.com/urbanopt/geojson-modelica-translator/files/3848782/versions.txt)

**Comment by nllong** [comment] 2019-12-06 15:13
It looks like the py tests are failing because it is running the teaser tests (e.g., `src/teaser/tests/test_tabula_ab.py`). These are not part of the geojson translator.

I'm not sure why there is a src/teaser/ directory in the geojson translator project, could you remove it? (back it up first just in case.)

**Comment by AntoineGautier** [comment] 2019-12-18 15:34
In pip editable mode (`-e`) the repo is first cloned in the current directory under `src`.
However, next to the cloned repo there is a file named `pip-delete-this-directory.txt` which contains the following lines.
```
This file is placed here by pip to indicate the source was put
here by pip.

Once this package is successfully installed this source code will be
deleted (unless you remove this file).
```
But what is described in that file is not executed. Furthermore if I manually delete the `src` directory the `teaser` module is not found any more. 
I have the same behavior on Ubuntu and macOS.
Note that I work in a conda environment: that could be a reason.
When installing without `-e` option, all tests pass.

**Comment by nllong** [comment] 2020-02-18 21:46
@AntoineGautier -- are you still seeing this issue? If so, can you clone this project anew and try running `py.test` from PR #32 branch? I am unable to recreate this issue.

I don't see how the version of python would matter. I'm mostly concerned about why there exists a `src` directory..

**Comment by AntoineGautier** [comment] 2020-02-19 22:31
Same as before: from a clean conda environment, checking out the branch `22-update-dependencies` and running:
```
pip install -r requirements.txt
python setup.py build
py.test
```
I have a persisting `src` directory from Teaser and the tests discovery routine exploring that directory. That leads to the errors in the screenshot.

![Screenshot from 2020-02-19 14-24-11](https://user-images.githubusercontent.com/10965994/74882719-711ee680-5324-11ea-8e83-cb527da16ebf.png)

**Comment by nllong** [comment] 2020-02-20 17:25
This is mind-boggling. Trying to recreate in a clean (docker) environment. Ubuntu 18.04 or another target?

**Comment by AntoineGautier** [comment] 2020-02-20 17:39
Yes I ran the tests on Ubuntu 18.04.
(I also tried before on macOS where I had the same issue.)

**Comment by nllong** [comment] 2020-02-21 00:18
Okay, I was able to recreate this. I don't use system python locally but was able to get the same error when using system python in Docker. The error was caused by teaser being checkout out into `./src` obviously and then py.test trying to run those tests as it aggressively searches for any test_* files. 

I fixed in the `22-updated-dependencies` branch by 1) using the teaser that has now been released on pypi, and 2) excluding the src directory in the py.test config. Can you give branch `22-updated-dependencies` again when you get a chance @AntoineGautier? Thanks!

**Comment by AntoineGautier** [comment] 2020-02-21 01:26
Solved. 
(Also the `src` directory does not persist anymore.)

**Comment by nllong** [comment] 2020-02-21 01:28
glad to hear. Yeah, it doesn't persist since we are pulling TEASER from PyPi. If good, can you approve PR #32? Thanks!

**Closed** 2020-02-21 03:42 UTC
